{% set name = "pylibftdi" %}
{% set version = "0.24.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e2229bc10d077f018cbe7b2b490227b2b538643fa6f7bff132cde15549ca129b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.4
    - pip
    - poetry
  run:
    - python >=3.4
    - libftdi

test:
  imports:
    - pylibftdi
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/codedstructure/pylibftdi
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Simple library interacting with FTDI devices to provide serial and parallel IO from Python.
  doc_url: https://pylibftdi.readthedocs.io/

extra:
  recipe-maintainers:
    - wvreeven
