{% set name = "pylibftdi" %}
{% set version = "0.20.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f4a87fc4af2c9c7d42badd4192ca9b529f32c9d96fdc8daea7e29c509226df5f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.4
    - pip
  run:
    - python >=3.4

test:
  imports:
    - pylibftdi
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/codedstructure/pylibftdi
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Simple library interacting with FTDI devices to provide serial and parallel IO from Python.
  doc_url: https://pylibftdi.readthedocs.io/

extra:
  recipe-maintainers:
    - wvreeven
