{% set name = "pylibftdi" %}
{% set version = "0.22.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 85a6aab438f765342843aa2d59bb28fbb0d30847a621fb9800985185990f01af

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.4
    - pip
  run:
    - python >=3.4

test:
  imports:
    - pylibftdi
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/codedstructure/pylibftdi
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Simple library interacting with FTDI devices to provide serial and parallel IO from Python.
  doc_url: https://pylibftdi.readthedocs.io/

extra:
  recipe-maintainers:
    - wvreeven
